project_id = "aahtjjolpmrfcxxiouxj"

[functions.consulta-fipe]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.test-smtp]
verify_jwt = false

[functions.password-reset-request]
verify_jwt = false

[functions.password-reset-confirm]
verify_jwt = false

[functions.reports-chat]
verify_jwt = false

[functions.sync-to-ga360]
verify_jwt = false
